spring:
    application:
        name: LogKey

    # DB 설정
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver

        url: jdbc:oracle:thin:@13.125.37.74/xe
        username: springkmg
        password: java1234
    # JPA 설정
    jpa:
        database: oracle
        generate-ddl: false
        hibernate:
            dialect: org.hibernate.dialect.Oracle11cDialect
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
    port: 8090